apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Z5Rzw8eA6Ebtm+fe2g==,iv:IhbuQBvM3HX0eJ8zdOZwoIYJUvlB7qc5rMTMuLQ3AIg=,tag:FQn1SkHIwoFsb+XXXOT+Ow==,type:str]
    password: ENC[AES256_GCM,data:36TbaliynHKzao3KsUXxKF8x40TBJY2OmSq14a16TzM=,iv:c2wAtYb92VCN3I03yniWvIWuEEKowVDpEHlprAdic4Y=,tag:qKXsBUL9RGzbWW63r2nH6w==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQVRROU4ra3ZWZmlYMXlR
            T2Z2akpLMzlORHFLd2JhZ2RoUlRYenpqelh3CmV1RDMxQ1RaSzJpM1hKcXZHR3J4
            R3pqdXBQYWpRUU04OEFLQURJeEF5OHMKLS0tIEFUL2pZRG5zU0s4WjE4NGkzUjRR
            eUVwSnJ5NE9KN3ZSUmpSd0hGSUk2TjQKXeDIXrNTqm/oc9JAPSV6shx6lFvDK2rZ
            h4W3TjU8YjbBZUbb7gP9snxymKEiDpf0z+dgnSHIjdt7xoa8K43o+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T15:05:39Z"
    mac: ENC[AES256_GCM,data:tYyGGq+3Uu0871IKlRXKKk8IzZ5f+RJTyS/UrHVXuMgF2qCMHzh7AFdX0BGJ4k2+B4uwmQKkMPoIrN8ohct3TiZ5JoDa+jKrRSougL2zIWOXun10pleGetinHwxLPY134m1YGyBRhCnFth+tJoTOvt5SHZJX8iP6sCaoSOebfV4=,iv:VQbSI1Bz+S2pCKd4wKeDdn/fqMLYCiyvtP4OCWYCj1c=,tag:M5yiGOiHIud6TWZcUdAM2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
