apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-gpu
    namespace: forgejo
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Srw7TQxeh+ierou+lEqKR6zsNbkMoEMsly7wFBD5dhQlymxmf8KTQAsQ9Q==,iv:BeoFdKq4pxKzxDmp1f0ZavpodNU3bOdRLQS0vl+QiUo=,tag:JS473+zKnPUZ6Jjrwwpb9Q==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c2hjeVN6RGNZK3pXVmJN
            VDcyZUpqU0ZscGZJRGxhYzIyN2hlUk81cFFVCjBWQldYNnVOVVZnSlg3OEd6T3FS
            d3k5OEdBSWs0ZnlpL2NER1BnMGUwV1kKLS0tIFROS3d0Y0RGN3Nzb1BpU0hKdW9a
            UUtLcG1oelU3L3ByaGNPRUl4dHpxU2sKfifqyq4k9BT0NdNzQCFLi9Zvrg8NhMFm
            kiNO7tuZ0fe4e9PHvl02opMrXl6owk8OUV4UHlFIpJIN3YDXm1MmXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T20:39:56Z"
    mac: ENC[AES256_GCM,data:p95PLhjgwjeM2o68snLA1dXyBjziMWaGeuuo7hy1R/70OI5Gu7CKbGPzLlvD8K4IMSUnqSeEeNs6MqchhngAvNBFGP073fHEraZkmh2wQRGawkgLmjYRSrlU0h3fMFUw9ApKYXHAc/5eE5MMNlnLldUqjRPuzPN7kBqnsXmeEY0=,iv:ped0QMyJfdUV1Zx8B1ZXD/9e1TQQub9D0hJFnMxmzHY=,tag:j4G8HJq9oqNi+ea5Ewi28g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
