apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner
    namespace: forgejo
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:g/H0oL7xEOR+x0vA5EhW7Us8IbXTFzBJ3m+oTz2jxwg/LUgcN5ztLA==,iv:Q3+yzSXO8yUBG41HRaCYp9QBFOqbzmoMz/cumKcRPxU=,tag:WSYeb4KjtiCXAPnKsS6zgw==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbWdCbjNLcjFLK09NT21x
            MEp4WHZaN3dYdE9sajFDU0ZiZW5jVmNNbnpRCkhiYjdUQjlwV2h2Y0h4RytFSW9q
            SC9mOFF6Wm1ZN1BqQUo5TjJCREJlM2MKLS0tIFRwQXRwb1FTOTBpTTVLUUZ5YlQv
            cnoreXBNa29jRFdIdlNjV1RpVzR4YVUKZSFiHgvzI6PV/hacNV12K5hEI6SWM0n2
            KBDq28FfSLgNAnSGKmRu98r5YMK8fh3+25W4UNj9xHlyQbxGRXYu1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T15:38:52Z"
    mac: ENC[AES256_GCM,data:Iw0jsqaD2Lh7CoGHyH8pgDr+EqxFyp5bKUGzd3+ueUNyJJoSezE5C0q7Eu3vyoJ77TcV1fX4w4Pse1WZHZgy+vdhhBvCrx+sKyyf3KUx4WH3zMZ1ZdU8sXZx718ctR+bZYe5fc52I+THeTUXIvhA9eVzZhYLvwcUEgAz/erI0VI=,iv:Z09XFmvqG2RZddoBgB7R/NipswS5hGmsoVDWCyqqHNY=,tag:6HdapiG8x1pkhHZ9Ju6sJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
