---
# HelmRelease for Grafana Alloy
# Log collection agent running as DaemonSet on every node
# Collects container logs and ships them to Loki
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alloy
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: alloy
      version: '>=0.9.0 <1.0.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h

  targetNamespace: monitoring
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    # ==================================================================
    # ALLOY CONFIGURATION
    # River config defining the log collection pipeline
    # ==================================================================
    alloy:
      configMap:
        content: |
          // ============================================================
          // KUBERNETES LOG COLLECTION PIPELINE
          // Discovers pods, collects their logs, ships to Loki
          // ============================================================

          // Discover all pods in the cluster
          // This provides targets with labels like:
          //   __meta_kubernetes_namespace
          //   __meta_kubernetes_pod_name
          //   __meta_kubernetes_pod_container_name
          discovery.kubernetes "pods" {
            role = "pod"
          }

          // Relabel discovered pods to extract useful labels
          // These labels will be attached to log streams in Loki
          discovery.relabel "pod_logs" {
            targets = discovery.kubernetes.pods.targets

            // Keep only running pods with a container name
            rule {
              source_labels = ["__meta_kubernetes_pod_phase"]
              regex         = "Pending|Succeeded|Failed|Unknown"
              action        = "drop"
            }

            // Set the namespace label
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }

            // Set the pod label
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "pod"
            }

            // Set the container label
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }

            // Set the app label from pod labels (if present)
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app"]
              target_label  = "app"
            }

            // Also try app.kubernetes.io/name
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
              target_label  = "app"
            }

            // Set the node label
            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label  = "node"
            }

            // Build the path to the container log file
            // Talos Linux uses /var/log/pods/<namespace>_<pod>_<uid>/<container>/*.log
            rule {
              source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
              target_label  = "__path__"
              separator     = "/"
              replacement   = "/var/log/pods/*$1/$2/*.log"
            }
          }

          // Collect logs from discovered pod log files
          loki.source.file "pod_logs" {
            targets    = discovery.relabel.pod_logs.output
            forward_to = [loki.process.pod_logs.receiver]
          }

          // Process logs - parse timestamps and add labels
          loki.process "pod_logs" {
            forward_to = [loki.write.default.receiver]

            // Parse CRI log format (containerd)
            // Format: <timestamp> <stream> <flags> <log>
            stage.cri {}

            // Add static label identifying this as k8s logs
            stage.static_labels {
              values = {
                job = "kubernetes-pods",
              }
            }
          }

          // Ship logs to Loki
          loki.write "default" {
            endpoint {
              url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
            }
          }

    # ==================================================================
    # DAEMONSET CONFIGURATION
    # Run one Alloy pod per node
    # ==================================================================
    controller:
      type: daemonset

    # ==================================================================
    # RESOURCE LIMITS
    # Keep it light for Raspberry Pi
    # ==================================================================
    resources:
      limits:
        cpu: 150m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi

    # ==================================================================
    # VOLUME MOUNTS
    # Need access to node's log directories
    # ==================================================================
    mounts:
      varlog: true     # Mount /var/log from host
      dockercontainers: false  # Not using Docker
