---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: step-issuer
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: step-issuer
  chart:
    spec:
      chart: step-issuer
      version: "0.10.x"
      sourceRef:
        kind: HelmRepository
        name: step-issuer
        namespace: flux-system
  install:
    createNamespace: false
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # Replica count
    replicaCount: 1

    # Resource limits
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi

    # Prometheus metrics
    metrics:
      enabled: true

    # Webhook configuration
    webhook:
      enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 64Mi
