---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jupyterlab
  namespace: jupyterlab
spec:
  parentRefs:
    - name: goldentooth
      namespace: gateway
      sectionName: https
  hostnames:
    - jupyterlab.goldentooth.net
  rules:
    - backendRefs:
        - name: jupyterlab
          port: 80
