---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redirect.yaml
  - ntfy.yaml
  - grafana.yaml
  - prometheus.yaml
  - hubble.yaml
  - httpbin.yaml
  - jupyterlab.yaml
  - forgejo.yaml
  - mcp.yaml
  - pds.yaml
