---
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
  namespace: jupyterlab
  annotations:
    gatus.io/enabled: "true"
spec:
  type: ClusterIP
  selector:
    app: jupyterlab
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
