---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: theatre
  namespace: flux-system
spec:
  image: registry.goldentooth.net/goldentooth-theatre
  interval: 1m
  insecure: true
