---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: theatre
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: flux@goldentooth.net
      messageTemplate: 'chore(flux): update theatre image to {{range .Changed.Changes}}{{print .NewValue}}{{end}}'
    push:
      branch: main
  update:
    path: ./apps/theatre
    strategy: Setters
