---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theatre-data
  namespace: goldentooth-theatre
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
