apiVersion: v1
kind: Secret
metadata:
    name: theatre-secrets
    namespace: goldentooth-theatre
type: Opaque
stringData:
    anthropic-api-key: ENC[AES256_GCM,data:MjewHvJVC/cKFDloSXU8YSyz2A+kedRph1lhdY2izqs13gfS5ijmAZ9qBg6VqT1k0Nd4z48dRQSuTi5eWujVNGEV+mCnyg1f117sqB9VvDMAfKVJt3XMH+CriHyTUv21qI2eduMyZbFK/b1b,iv:vF7lOhv0ksf3E46VFLWMv317B9yRx1Zje8eJxylre3Q=,tag:8BUrax71V5r+rNzpXr5xng==,type:str]
    openai-api-key: ENC[AES256_GCM,data:w3o/9bHPXbCg5XtplXyqrh2Q5UX+pPT81oaMThV9EZ7hZvueHiFyX6Y9K80V4BisH+Oc,iv:guLOLoHwj1t38rXPyA+oGIcR2wpY07o8H+X6gbKY5/o=,tag:kWLgMhdT7uyzjH8k17xO2w==,type:str]
    forgejo-token: ENC[AES256_GCM,data:DKxIaoh/mNxG7gIpZfHJ1yxqU0YPk1SDovPoRVfmZWSbUf18Kz3IPg==,iv:/XUHHIYFvvHftEB7PonRITp+9V797SBEobkdjg5J+t4=,tag:ZL7bGqiJ20bVTdmg9pWVaA==,type:str]
    atproto-passwords.json: ENC[AES256_GCM,data:B/3ROI+CRmRC90hjmtmzi/7X93xL8mESmaH0gBh1CCSqtuB+EtiA9yzdPU/4bgMtiRxmUnKXGERDyp1z44OJwVICX01RsMW479Ydj1fMzQAqfR97dyn+a1asST4MtBuh5D1AUO6qe87/,iv:2RiwDLoOjgcGYi6nfTCH2Z1l3xxRosDBIiEHh7q8/qM=,tag:a6xaOBehbL03dhBqGIk3YA==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dG1sSm56QTIyQnhjY0Mv
            c3A1K21FbjE3TXRRTWhwSGtNYjRteXZ3Z21rCmRSME95Sjg4N05PR2I4QThLdjc3
            Z3h5bEJTQmlVS0M2YVdqTzRzMHFJK2MKLS0tIHRUeHBIS0FaQTNEK3NBMFNlSVBk
            OVdzNXY4SW84YjZZNWd4UXJnRm0vejgKOTAAajchPEXyEytowAfBgM9TJNaPMw4i
            24arnRfiEiGy7sP8beKSrFu4FPxFpppZl3y0mwTBHFTDaA36gJOOqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T18:41:02Z"
    mac: ENC[AES256_GCM,data:UYof0p5yp3vyAiRzb3jztEUyxHbnkGlXfp9UALM5CLIXJAa+lZiubj/nk422sMQ7dqZUfeyXxNMDzor1uPoGukYkbOEhvtTtuXt9TnNTfqPsf+Pubm2cL13/ctedZ2+C/0Rh+TusiELjqZpgamB8LDOxc4As6ygO9skPDFl3pWU=,iv:YJQQXYOfm29x+Cdgy/7hixEU91P0S/vMzdcyZ73pTgw=,tag:hlTfuYVv4smFL1hw76cJUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
