apiVersion: v1
kind: Secret
metadata:
    name: theatre-secrets
    namespace: theatre
type: Opaque
stringData:
    anthropic-api-key: ENC[AES256_GCM,data:VB0FByZPRjRJjiDPb1E2PlACYhoUIzAbO7gtxCjWQdUiii1ZjGax4W9CEWOsKKVPEtz89XXuTKJAxaDii5k07baDQGft78w8G76+SQCn+ddTR3ZnxCjg58i0QOmo+iR6gdRbmd8saPfPx455,iv:8lKXcDHZpC8/j4umQQneY0Lr2XEdISJHBLGPG4mODEI=,tag:YQ0N7qyi0jxBxXJ7yp7UFA==,type:str]
    openai-api-key: ENC[AES256_GCM,data:2XxJT4YniDwKM1fZriLPSQJ66zuNzlflrQ98Im4we9B7MT8hh5tKZXFRLYxFJvtWFehf,iv:i0HJjeY3os0ePljgJ+ycHXsS8ioNkVWGPWbJq7am3T8=,tag:9B7xn/xVJl8Zt4E+psY8bw==,type:str]
    github-token: ENC[AES256_GCM,data:nFaruqRP2N+1wSE6WD/n5Y1brttu3vhrrPI2MG7MBhYI1ftuEpL/vsk/ON3sfBAzFJzLUh9+Og11yGviX4yhaBgaC/6iTBGTQsT402hKgpfbNkQFbnjrli68YfH6,iv:wikceDg9yvgumcb7LgnCkK2H+uDVzyDwrHyG2xY3zXg=,tag:5dB1Na+ATIq256lYSMEs7g==,type:str]
    atproto-passwords.json: ENC[AES256_GCM,data:LSqYJEzuAAkQo/UvyaqYnCkgZUgKXX/USPxuxlT40MsTO1N2e/PWiMJnKRjS1A4XX4SduFdL6R3x65H4lw8hKeUDex6KJayT80LcAc+M0wgrdVyxibOM6TAY12adIs/ZLQ3DnvKxTTBe,iv:d7n9SrN5r+v8nCA6tyXq5NywF7jDzO9Lz7XRXUn6ieg=,tag:vg1XM1nNM7CRQC863X2zew==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLM3NZWVllTWEwVk5HZXVZ
            TlFINEh3ZGE0L1VVWTE2SzMrM21yUjhPbUI4CkFtaW05QzVGK1VYUTFxczA0NGxr
            UzJjUFhtbFd0bzJNV1ZhZmpiRHFEKzgKLS0tIFd3bmxPVmZpQmNteVo5b1Y1Ym9i
            NDFzL3l6SE5raGNPeWlxU1dtbnBPQkUK2fMV4CN8ItB1lwnrPpgMcGDm6H1XfaZa
            jE7sNjtAB7lj8fct9m4HoEiMqgF5xr34/2plxTeNFjzrOfr1QL94GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T21:35:09Z"
    mac: ENC[AES256_GCM,data:Ze/q1crvIgzzDoA2T1pZNPPkrw4V8FySUnaMZtqZolYyQfXNSI6p37vdMo42uzB/j4X48Q+39SeRfbnuQ7FAXfcD3YhcOYNuruqXl5qUYpoqws7+Rc0bQF7M2lJwn3A1UkJ657or8RTwNf/1GM617+SXmOd41VMEsYn+sIhTsPk=,iv:33HCMTCEe8K3owJzNZgyl+GuDiIf39d/WV07DyHRNy0=,tag:zBqDN7dC/RE41T+dFuymIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
