apiVersion: v1
kind: Secret
metadata:
    name: theatre-secrets
    namespace: goldentooth-theatre
type: Opaque
stringData:
    anthropic-api-key: ENC[AES256_GCM,data:/8ZFCVGUqJCS+ptuPi6vKN4YzcRvS+pQdGjuXr/L1f4dGFyM8GOyCBlxRDbTMh1Emdw72vmJXSenD+CC8JxE0hG1/phsG6mxSt6evP8kHyBQV3sOa+E/yfDQoiGWJ8bY27S2VkQSrvWZ5R7J,iv:DdObOgGfpbnM1M+oBhQt6Fugbe+8yIN8h/9ln9atl74=,tag:nzLvYpz2CETMPuwUByzFVQ==,type:str]
    openai-api-key: ENC[AES256_GCM,data:b0Xui3E/jjDiTbinCs24GkJtGaHfU+BwsjY7uiPpl1LsX3Lggj8Q6uJxRVnJgi8DO+21,iv:bMR7hi4bXGXTFXAqnLaVP0D4IvGoxjH9nkMRAN7vuM8=,tag:x5QFSAsZfFOwlf+9yuo4SQ==,type:str]
    atproto-passwords.json: ENC[AES256_GCM,data:3SXzVb69bTNrdjK/ytOlnavr/ycUAopuTwXWKgtPA3cleALwFME=,iv:eA6iacuR/K4AG+1WjmgYHY4NQxEznILp7v89KrDfKZc=,tag:vEj2tpBdJOK6D1LxtWmyLA==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV2k4Ris4b3l3bm8wQXp0
            ZG1HMmNaaXVEcm44RmFCVzZ0WVUzRGd3K0JzCnNldnhkL3BiRW42UHBzYnloODBt
            dGJFZW9yWkQxT3pqWHhsdDNCWGhNSkEKLS0tIFY3MU1UVkc0cGg2L1BMVjgyNzFh
            S09iMFRoTU5jTzJJU095bWNPS1RGVlEKDPt981+fMXfvCf04h/dSFXp2WFii/Dow
            2j7wqRT/QrZ9HSCoZAvNiHWd/mW7pPjx28B+wYQxR1Yydlsjfd/ZJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T00:06:56Z"
    mac: ENC[AES256_GCM,data:2UzUY2h98QcPgrwmpN16k8TG6jr7dnqPdFuY/qlslYsBErWvUPtQMn/mRYraPG4U/r9lj4YA7sHDb5d1c+6f9S5o0yXxxNE7veeR16tdfoTYRmIwcBA6OGvYOTthDpOnCdIZRAs6UxxHoyvXxyxouCIurrJpGUZqU59pnisYDBo=,iv:6qMus0ozwGOFEof2v8CRMizF3icwkYiBvuuLe6DB068=,tag:bD7s19Kseos7gChZDzVn1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
