---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./infrastructure/goldentooth"
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age