---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "1.16.2"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  install:
    createNamespace: false
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # Install CRDs as part of the Helm release
    crds:
      enabled: true

    # Global configuration
    global:
      leaderElection:
        namespace: cert-manager

    # Prometheus metrics (ServiceMonitor disabled for now)
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false

    # Resource limits for the controller
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi

    # Webhook resource limits
    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 64Mi

    # CA Injector resource limits
    cainjector:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 128Mi
