---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: litmuschaos
  namespace: flux-system
spec:
  interval: 24h
  url: https://litmuschaos.github.io/litmus-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: litmus
  namespace: litmus
spec:
  interval: 30m
  chart:
    spec:
      chart: litmus
      version: ">=3.20.0 <4.0.0"
      sourceRef:
        kind: HelmRepository
        name: litmuschaos
        namespace: flux-system
      interval: 12h
  values:
    # ==================================================================
    # CHAOSCENTER FRONTEND
    # ==================================================================
    portal:
      frontend:
        service:
          type: LoadBalancer
          port: 9091
          annotations:
            metallb.io/address-pool: default
            external-dns.alpha.kubernetes.io/hostname: chaos-center.goldentooth.net
            external-dns.alpha.kubernetes.io/ttl: "60"
          externalTrafficPolicy: Local
        resources:
          requests:
            memory: "150Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "550m"

      server:
        graphqlServer:
          resources:
            requests:
              memory: "250Mi"
              cpu: "225m"
            limits:
              memory: "712Mi"
              cpu: "550m"

        authServer:
          resources:
            requests:
              memory: "250Mi"
              cpu: "125m"
            limits:
              memory: "712Mi"
              cpu: "550m"

    # ==================================================================
    # MONGODB - PINNED TO VELARYON (x86 node)
    # MongoDB doesn't support ARM64 well, so we run it on the x86 GPU node
    # ==================================================================
    mongodb:
      enabled: true
      architecture: standalone

      # Pin to Velaryon (x86 node) since MongoDB needs x86
      nodeSelector:
        kubernetes.io/hostname: velaryon

      # Tolerate both taints on Velaryon
      # - gpu taint (even though MongoDB doesn't use GPU)
      # - platform taint (MongoDB needs x86 architecture)
      tolerations:
        - key: "gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "platform"
          operator: "Equal"
          value: "x86"
          effect: "NoSchedule"

      # Use official Bitnami MongoDB (works fine on x86)
      # Using latest tag since Bitnami now only offers latest for free tier
      image:
        registry: docker.io
        repository: bitnami/mongodb
        tag: "latest"

      persistence:
        enabled: true
        size: 5Gi
        storageClass: "local-path"

      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"

    # ==================================================================
    # INGRESS (disabled - using LoadBalancer)
    # ==================================================================
    ingress:
      enabled: false
