---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: litmuschaos
  namespace: flux-system
spec:
  interval: 24h
  url: https://litmuschaos.github.io/litmus-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: litmus
  namespace: litmus
spec:
  interval: 30m
  chart:
    spec:
      chart: litmus
      version: ">=3.20.0 <4.0.0"
      sourceRef:
        kind: HelmRepository
        name: litmuschaos
        namespace: flux-system
      interval: 12h
  values:
    # ==================================================================
    # CHAOSCENTER FRONTEND
    # ==================================================================
    portal:
      frontend:
        service:
          type: LoadBalancer
          port: 9091
          annotations:
            metallb.io/address-pool: default
            external-dns.alpha.kubernetes.io/hostname: chaos-center.goldentooth.net
            external-dns.alpha.kubernetes.io/ttl: "60"
          externalTrafficPolicy: Local
        resources:
          requests:
            memory: "150Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "550m"

      server:
        # Pin to Raspberry Pi 5 nodes (ARMv8.2-A support)
        nodeSelector:
          cpu.arch: armv8.2-a

        graphqlServer:
          resources:
            requests:
              memory: "250Mi"
              cpu: "225m"
            limits:
              memory: "712Mi"
              cpu: "550m"

        authServer:
          resources:
            requests:
              memory: "250Mi"
              cpu: "125m"
            limits:
              memory: "712Mi"
              cpu: "550m"

    # ==================================================================
    # MONGODB - PINNED TO RASPBERRY PI 5 NODES
    # MongoDB needs ARMv8.2-A CPU instructions (Pi 4 only has ARMv8.0-A)
    # Single-member replica set (not standalone) because Litmus init
    # containers check rs.status()
    # ==================================================================
    mongodb:
      enabled: true
      architecture: replicaset
      replicaCount: 1

      # No arbiter needed for single-member replica set
      arbiter:
        enabled: false

      # Pin to Raspberry Pi 5 nodes (ARMv8.2-A support)
      nodeSelector:
        cpu.arch: armv8.2-a

      # Use official Bitnami MongoDB
      # Using latest tag since Bitnami now only offers latest for free tier
      image:
        registry: docker.io
        repository: bitnami/mongodb
        tag: "latest"

      persistence:
        enabled: true
        size: 5Gi
        storageClass: "local-path"

      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"

    # ==================================================================
    # INGRESS (disabled - using LoadBalancer)
    # ==================================================================
    ingress:
      enabled: false
