---
# TLS certificate for Docker Registry using Step-CA
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls
  namespace: docker-registry
spec:
  # Secret where Registry will read the certificate
  secretName: registry-tls

  # Certificate duration (24 hours)
  duration: 24h

  # Renew when 2/3 of lifetime has passed
  renewBefore: 8h

  # Subject information
  subject:
    organizations:
      - Goldentooth

  # Common name
  commonName: registry.goldentooth.net

  # DNS SANs
  dnsNames:
    - registry.goldentooth.net

  # Issuer reference
  issuerRef:
    name: step-ca
    kind: StepClusterIssuer
    group: certmanager.step.sm
