apiVersion: v1
kind: Secret
metadata:
    name: registry-s3-secret
    namespace: docker-registry
type: Opaque
stringData:
    accesskey: ENC[AES256_GCM,data:1hXX+NyPUwmakzwVKWZFFJX/0GmNv18giH4=,iv:7eAKoXJ/VT9a6RGTTcJm2xSj52YzBrqm6ma0CdhhrfU=,tag:ufOnEVxc27chwVZDRc3SMg==,type:str]
    secretkey: ENC[AES256_GCM,data:PI07SS+xGfiQyUD2ls/LMZLzFKQMqEiW9/r/Xflaa0mc39lqRXZi8t2CUxKn50O3mKegS4o/kbVWG/fZF78OFw==,iv:NfUIcUSRLpun1xNJZ87EfslcvpiZMpPErEpbKdRRd/4=,tag:BsXm2SZo4AqHsvMd+LNJJA==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTEorVEJOVDd6MytWdnRD
            UDhsRWZyUm8zOWg3dFZ5NjBlNmlNUWwrd2lBCkpnd09kT0x0SU9KTTllaVUrekM0
            aWViL3MrVVgzbkhMSjQvaEpqZUFnZkUKLS0tIE95SnZvbURPSTR4WkRVcnZpSWZ2
            dU8yWjhHTHlRRjloTUNMUG1STmNGTEkKHyM3uQ9Nnm3qnNijoTClsjy4iWx5zRPL
            4PmmKt0607WZwsBrHQzNb8zHx23KK++P6GnUUBmoTkyksMP/fwcdUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T04:14:32Z"
    mac: ENC[AES256_GCM,data:sFcE65AcYjR1MlyK7WyK4YQSNRHb19WVU7e3zAM1JUa92o2urbDwh3Su1yJR3jymRRJ9UGNNg4cz/Nv7/cCp5JyqKw6fWmt5V553kwZs9epmihu3YyZlUY5FitxOhVyMrle5z+ac/7EO3kruuWJngo/zVTnAKjdbGlORyTXAFXY=,iv:pqnuCLwMvUqOkgokWzcCLZ2zzvMBuc9oWJd8v3kWhJ8=,tag:Mv5yOsaugr41u01/dv+ysQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
