apiVersion: v1
kind: Secret
metadata:
    name: registry-s3-secret
    namespace: docker-registry
type: Opaque
stringData:
    accesskey: ENC[AES256_GCM,data:MUHWdRPOcZya5j8IPRi0,iv:RBqWjF0b5yTNhPwh7op6MKut24YMusWPqdgdyrtkv3o=,tag:aZpcbCFU1GrYkXRRlrxPJw==,type:str]
    secretkey: ENC[AES256_GCM,data:WE103EomT97d4hBSx+L+vY9cc2XnCm7wGlTRulLlxQe15l6ZxUUxac3hqGc=,iv:Eh/Q+YGx58DczLiwcTR3vUt/9G53Eah8vSsS0VN8COw=,tag:lIeJ8646FkX4YWyIPjTpQw==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b1NYcjRCVnovV3ZmMHN2
            VGNNNmZyTm4xV1Jyd3FOY2VBRldsS3Rwb1ZvCldjN2JGaVZsaEJZZXVRZVJlOFpH
            bmhSRFZvb1AvOHJOY05va0lsUm9qc3MKLS0tIHJXd2NWS2dXRkRmQnVEazJQWElJ
            RktKY0RMZ3hvbVNEeE1SNXpJenRZK1kKutq0KKkcyF598kVoMQF7gNMo3BqPPMdY
            72glza5YPLaimOtSoAOcntlgfM+shX+jQaQ28PVP+EdwqDARz4r66Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T19:34:09Z"
    mac: ENC[AES256_GCM,data:bxcSs2U9M5uDdyiQ6PTmi8RHmO8MzsW+uLoegSJzRW4pKAKN4W5DTZ7U/9t4AV79MHCHgA782/97clHB89T73vgmHzH8KR5sVnV3G2DrV8My8ryY0l+tcqJOwblgL85I7WHqZO0DTbIuE3UdA1JZi2iFWPnW28Znz65d16Ni9tU=,iv:42299nxFRAOW75jBp3PM5B/N4ZnQnFeRyPBJH/FOoCY=,tag:REAMUTmLics+TwYqtjNjgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
