apiVersion: v1
kind: Secret
metadata:
    name: registry-s3-secret
    namespace: docker-registry
type: Opaque
stringData:
    accesskey: ENC[AES256_GCM,data:4dB97PHBGlKcCA5PYTJHIhaoJcDsx4eWrv4=,iv:N8kUYDWvGpHryyem3+hF4ZtkA1eut1otwGN+g/7hRhg=,tag:CkbtE9YahVXyuoBxbUHrQw==,type:str]
    secretkey: ENC[AES256_GCM,data:e/tATcAO5Hzj5VuskQnORmTskYIxJkSsGSsOIHywNiXk1TE4VZQqSv6/rdKV4MT+muQWVqn1R6ZzrkfQUut/NA==,iv:yzpvkNtjqndK0g2NPlxkL/XnUx8hS9jKojqSEsU0APw=,tag:KTofvh9UEF5/ePCbrGgMqw==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MkNCYTFkTWx4ZmFRZTNK
            d2hnSWsyMEpkWDZudE5rSXZ1UG55WisrM2lrCldLRmV5cFFLYkRCdVhxUkJvUTdv
            M2tyWW1EMjR5QUF1SG5BeXNHeXZsREUKLS0tIHRxN1o5aGFOcUFaelFEeE50NW9o
            THplUm0xOWdYV0d2eWhqZjMrVnpma00K/Vv/3Nr37dXt+R5WjkgjFpos/zifHnzB
            hOaOITOGdrZuuPw0guQ7yDI4gI/QpeKaZFmsaPqblZx6lfRSE2xMHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T16:30:34Z"
    mac: ENC[AES256_GCM,data:l7QnbZLB9Y04ILnUE89vObmdUbktxaVk+Q602ZHx6DRdTBHFd2z5BY/YtiWfIOvucXwxla4w2EqQOHAIYivg+CbcCdBevO+H9J2iL3QjYDkk76VF9cSK0ZfwSUiWR3ihZvMeUtl3L70l1x0A4SfcxObyXXSM3KnDAxVII+/TwZw=,iv:5mzhInWjajva3Pbdq+yppHCpjr+yTls+OwdgqzT922U=,tag:BwTVHdY5aeo6SCGodQkw9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
