apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-admin-creds
    namespace: docker-registry
type: Opaque
stringData:
    accesskey: ENC[AES256_GCM,data:6vg96ak=,iv:/YGKcgShWwEG/haQuzjxN7ynPRvWVtxtVj56GfC0bDU=,tag:QsJ0tu3ulvnlu8BMtJaBlw==,type:str]
    secretkey: ENC[AES256_GCM,data:1P0OuhA8+b1pnIysVgmza44SmnTnUE3dzK5AmVXazTX4T03g0DZBqwm/bgY=,iv:cXkjjZSxlCNnBp5SKDG7Euht9QexK4w7bmMOlrmWGak=,tag:OOFDbCzb55q1cp45WdXaVg==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYThFYytvWUZ0c3laNzBH
            bXVNcUEzaDdkakNxWm9mNWNRYUVKd2FzYVU0Ck5sYTAyVEF2b1pvZTU0OEUzK0E2
            Wm1EYkdGZUZ3cWFKVVcvbVZ1dWZsMTAKLS0tIEp3eEhYWjFsQ2NCcnFxUEhOZmtY
            OU9hKzh4RmRrSXNkaTBsM0IxUG1mRnMKehiQPSXriLJRG13gnaT03Js5IaY4Swai
            Rx+9kT10w37sgdDTfx3GFKnWJWubARrKDZm2ZFIG6kaiQyTv33hJgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T16:23:45Z"
    mac: ENC[AES256_GCM,data:hxj9n9f+opodY1gOV59LqnflJdtmAl+RmwR3s/6jXaUFXlpzbLCFrcJV3kS323p47I+FTSzmejM2OG8xTeoUrN0bx7tZU4EqG9XyqxO/EbgvexQ96HB+i5Up4FrYSOwiAeKFHebImM/HmpUIeLwYZG1xTI6I+JbisKfat9ll1eY=,iv:08DhEfFzeS0h5rTk0US6SAywE0xt/IzEeDUXYera8tQ=,tag:xOiN4ah7THx9Yz4yO7qkmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
