---
# StatefulSet for Steam-Headless gaming container
# Runs on velaryon GPU node with NVIDIA RTX 2070 Super
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: steam-headless
  namespace: steam-headless
spec:
  serviceName: steam-headless
  replicas: 1
  selector:
    matchLabels:
      app: steam-headless
  template:
    metadata:
      labels:
        app: steam-headless
    spec:
      # Use NVIDIA container runtime (required for GPU access on Talos)
      runtimeClassName: nvidia

      # Use host IPC namespace - Steam needs this for shared memory segments
      # Without this, mmap() calls fail when creating IPC shared memory
      hostIPC: true

      # Pod-level security context
      securityContext:
        fsGroup: 1000  # Ensures volume files are accessible by UID 1000

      # Schedule only on GPU node
      nodeSelector:
        role: gpu

      # Tolerate the GPU taint
      tolerations:
        - key: gpu
          operator: Equal
          value: "true"
          effect: NoSchedule

      containers:
        - name: steam-headless
          image: josh5/steam-headless:debian

          ports:
            # noVNC web interface
            - name: novnc-web
              containerPort: 8083
              protocol: TCP

            # Sunshine streaming server ports
            - name: sunshine-https
              containerPort: 47984
              protocol: TCP
            - name: sunshine-http
              containerPort: 47989
              protocol: TCP
            - name: sunshine-web
              containerPort: 47990
              protocol: TCP
            - name: sunshine-rtsp
              containerPort: 48010
              protocol: TCP

            # Sunshine UDP ports (video, audio, control)
            - name: sun-video
              containerPort: 47998
              protocol: UDP
            - name: sun-audio
              containerPort: 47999
              protocol: UDP
            - name: sun-ctrl
              containerPort: 48000
              protocol: UDP
            - name: sun-ctrl2
              containerPort: 48002
              protocol: UDP
            - name: sun-rtsp-udp
              containerPort: 48010
              protocol: UDP

            # mDNS for service discovery
            - name: mdns
              containerPort: 5353
              protocol: UDP

          env:
            # === NVIDIA GPU Configuration ===
            # Required for GPU access in containers
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
            # Critical! Tells GLVND to use NVIDIA for OpenGL (not Mesa llvmpipe)
            - name: __GLX_VENDOR_LIBRARY_NAME
              value: "nvidia"

            # === User/Group Configuration ===
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "000"

            # === Input Device Configuration ===
            - name: SDL_JOYSTICK_DEVICE
              value: "/dev/input/event8"

            # === Display Configuration ===
            - name: DISPLAY
              value: ":55"
            - name: DISPLAY_CDEPTH
              value: "24"
            - name: DISPLAY_REFRESH
              value: "120"
            - name: DISPLAY_SIZEW
              value: "1920"
            - name: DISPLAY_SIZEH
              value: "1080"
            - name: DISPLAY_VIDEO_PORT
              value: "DFP"
            - name: MODE
              value: "primary"  # Container runs its own X server

            # === Sunshine Streaming ===
            - name: ENABLE_SUNSHINE
              value: "true"
            - name: ENABLE_EVDEV_INPUTS
              value: "true"

            # === noVNC Web UI ===
            - name: WEB_UI_MODE
              value: "vnc"  # Options: vnc, neko, none
            - name: ENABLE_VNC_AUDIO
              value: "true"
            - name: PORT_NOVNC_WEB
              value: "8083"

            # === Steam Configuration ===
            - name: ENABLE_STEAM
              value: "true"  # Auto-start Steam on container launch
            - name: STEAM_ARGS
              value: ""  # Start with GUI visible (not silent)

            # === Optional Features ===
            - name: ENABLE_WOL_POWER_MANAGER
              value: "false"
            - name: ENABLE_SID
              value: "false"

          # Request 1 GPU from the time-sliced pool
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "8"
              memory: "16Gi"
              nvidia.com/gpu: "1"

          volumeMounts:
            # Steam home directory (config, SSFN auth files, saves)
            - name: steam-home
              mountPath: /home/default

            # Game library storage
            - name: steam-games
              mountPath: /mnt/games

            # Shared memory (equivalent to Docker's shm_size)
            # Steam uses /dev/shm extensively for IPC
            - name: dshm
              mountPath: /dev/shm

            # Mount entire /dev/input directory so Steam can discover input devices
            # Sunshine creates virtual devices here, Steam needs to see the whole directory
            - name: input-devices
              mountPath: /dev/input

          # Security context for container operations
          securityContext:
            privileged: true
            # Disable seccomp filtering - Steam needs unrestricted syscalls
            seccompProfile:
              type: Unconfined
            capabilities:
              add:
                - NET_ADMIN   # Network configuration
                - SYS_ADMIN   # Mount operations (fuse, etc)
                - SYS_NICE    # Process priority adjustment

          # Health checks - noVNC web interface
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: steam-home
          persistentVolumeClaim:
            claimName: steam-home
        - name: steam-games
          persistentVolumeClaim:
            claimName: steam-games
        # Shared memory volume (RAM-backed) - gives 2Gi for /dev/shm
        # Steam needs this for shared memory segments used by IPC
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi

        # Host /dev/input directory - contains all input devices
        # Sunshine creates virtual devices here, Steam reads from here
        - name: input-devices
          hostPath:
            path: /dev/input
            type: Directory