---
# Seaweed Custom Resource
# Declaratively defines the SeaweedFS cluster configuration
# The operator will create StatefulSets, Services, and manage the cluster lifecycle
apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: goldentooth-storage
  namespace: seaweedfs
spec:
  # Use official SeaweedFS image (multi-arch, supports ARM64)
  image: chrislusf/seaweedfs:latest

  # Master Configuration (Raft consensus cluster)
  # Masters use volumeSizeLimitMB for configuration, not PVCs
  master:
    replicas: 3

    # CPU/Memory limits for Raspberry Pi cluster
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

    # Raft HA configuration
    config: |
      # Raft HA with HashiCorp implementation
      raftHashicorp = true
      # Default replication: 0 datacenters, 0 racks, 1 replica = 2 total copies
      defaultReplication = "001"

  # Volume Configuration (storage servers)
  # Volumes use requests.storage and storageClassName for PVCs
  volume:
    replicas: 6

    # Schedule ONLY on nodes with USB SSDs
    nodeSelector:
      storage.seaweedfs/volume: "true"

    # Storage configuration for USB SSDs
    # Note: No volumeClaimTemplate! Use requests.storage + storageClassName
    requests:
      storage: 100Gi   # Each volume server gets 100Gi on USB SSD
      cpu: 200m
      memory: 512Mi

    limits:
      cpu: 1000m
      memory: 2Gi

    # Use USB SSD storage class
    storageClassName: local-path-usb

  # Filer Configuration (provides S3 API)
  # Filer uses persistence object for PVCs
  filer:
    replicas: 1

    # Enable S3 API (for Harbor)
    s3:
      enabled: true

    # Enable embedded IAM
    iam: true

    # Service
    service:
      type: LoadBalancer
      annotations:
        metallb.io/address-pool: default
        external-dns.alpha.kubernetes.io/hostname: s3.goldentooth.net
        external-dns.alpha.kubernetes.io/ttl: "60"

    # CPU/Memory limits
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

    # Persistent storage for filer metadata
    persistence:
      enabled: true
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi

    # LevelDB backend configuration
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"
