---
# Flux Kustomization that installs the Tekton Operator from vendored release manifest
# Release downloaded from: https://storage.googleapis.com/tekton-releases/operator/previous/v0.77.0/release.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-operator-install
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/tekton/operator/manifests
  prune: true
  wait: true
  # Health checks - wait for the operator deployments to be ready
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: tekton-operator
      namespace: tekton-operator
    - apiVersion: apps/v1
      kind: Deployment
      name: tekton-operator-webhook
      namespace: tekton-operator
