---
# Flux Kustomization that installs the Tekton Operator from upstream manifests
# Uses the official tektoncd/operator repo instead of the buggy Helm chart
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-operator-install
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: tekton-operator
    namespace: flux-system
  # Official Kubernetes installation path in the tektoncd/operator repo
  path: ./config/kubernetes/overlays/default
  prune: true
  wait: true
  # Health checks - wait for the operator deployment to be ready
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: tekton-operator
      namespace: tekton-operator
    - apiVersion: apps/v1
      kind: Deployment
      name: tekton-operator-webhook
      namespace: tekton-operator
