apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tekton-operator
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    tag: v0.77.0
  url: https://github.com/tektoncd/operator
