---
# HelmRelease for SeaweedFS CSI Driver
# Enables Kubernetes PVCs backed by SeaweedFS distributed storage
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seaweedfs-csi-driver
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: seaweedfs
  chart:
    spec:
      chart: seaweedfs-csi-driver
      version: "0.2.3"
      sourceRef:
        kind: HelmRepository
        name: seaweedfs-csi-driver
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Filer address - uses the ClusterIP service created by the operator
    # Port 8888 is the Filer HTTP/gRPC endpoint
    seaweedfsFiler: "goldentooth-storage-filer.seaweedfs:8888"

    # StorageClass configuration
    storageClass:
      name: seaweedfs
      # Don't make it the default - let local-path remain default
      defaultClass: false

    # Controller runs on any node (doesn't need GPU)
    controller:
      replicas: 1

    # Node plugin runs on all nodes (DaemonSet)
    # Uses OnDelete update strategy to avoid breaking existing mounts
    node:
      updateStrategy:
        type: OnDelete
