---
# HelmRelease for SeaweedFS CSI Driver
# Enables Kubernetes PVCs backed by SeaweedFS distributed storage
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seaweedfs-csi-driver
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: seaweedfs
  chart:
    spec:
      chart: seaweedfs-csi-driver
      version: "0.2.3"
      sourceRef:
        kind: HelmRepository
        name: seaweedfs-csi-driver
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Pin CSI driver to specific version instead of :latest
    # v1.3.6 supports mountEndpoint flag that chart 0.2.3 expects
    seaweedfsCsiPlugin:
      image: chrislusf/seaweedfs-csi-driver:v1.3.6

    # Filer address - uses the ClusterIP service created by the operator
    # Port 8888 is the Filer HTTP/gRPC endpoint
    seaweedfsFiler: "goldentooth-storage-filer.seaweedfs:8888"

    # StorageClass: uses name "seaweedfs"
    storageClassName: seaweedfs
    # Don't make it the cluster default
    isDefaultStorageClass: false
