---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/wave: "0"
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  annotations:
    argocd.argoproj.io/wave: "0"
  labels:
    name: storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
  annotations:
    argocd.argoproj.io/wave: "0"
  labels:
    name: networking