---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: metallb-system
  chart:
    spec:
      chart: metallb
      version: "0.14.5"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Enable Prometheus metrics
    prometheus:
      serviceAccount: metallb-controller
      serviceMonitor:
        enabled: true
    # Speaker configuration for L2 mode
    speaker:
      enabled: true
      tolerateMaster: true
      # Disable FRR for simple L2 mode
      frr:
        enabled: false
    # Controller configuration
    controller:
      enabled: true