---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: step-ca
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: step-ca
  chart:
    spec:
      chart: step-certificates
      version: "1.27.x"
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Replica count (only 1 supported)
    replicaCount: 1

    # Service configuration
    service:
      type: LoadBalancer
      port: 443
      targetPort: 9000
      annotations:
        external-dns.alpha.kubernetes.io/hostname: step-ca.goldentooth.net

    # CA configuration
    ca:
      name: Goldentooth CA
      address: :9000
      dns: step-ca.goldentooth.net,step-ca.step-ca.svc.cluster.local
      url: https://step-ca.goldentooth.net

    # Bootstrap configuration - auto-generate CA with JWK provisioner on first run
    bootstrap:
      enabled: true
      configmaps: true
      secrets: true

    # Inject custom claims for 24h certificate lifetime
    inject:
      enabled: true
      config:
        files:
          defaults.json:
            ca-url: https://step-ca.step-ca.svc.cluster.local
            ca-config: /home/step/config/ca.json
            fingerprint: ""
            root: /home/step/certs/root_ca.crt
          ca.json:
            root: /home/step/certs/root_ca.crt
            crt: /home/step/certs/intermediate_ca.crt
            key: /home/step/secrets/intermediate_ca_key
            address: :9000
            dnsNames:
              - step-ca.goldentooth.net
              - step-ca.step-ca.svc.cluster.local
              - step-ca.step-ca
              - step-ca
            logger:
              format: json
            db:
              type: badgerv2
              dataSource: /home/step/db
            authority:
              # Global certificate lifetime claims - 24 hour max, aggressive rotation!
              claims:
                minTLSCertDuration: 5m
                maxTLSCertDuration: 24h
                defaultTLSCertDuration: 24h
                disableRenewal: false
                allowRenewalAfterExpiry: false
            tls:
              cipherSuites:
                - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
                - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
              minVersion: 1.2
              maxVersion: 1.3
              renegotiation: false

    # Resource limits
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 256Mi

    # Persistence - use emptyDir for learning cluster
    # If CA is lost, we just regenerate - it's all in Git!
    persistence:
      enabled: false
