---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: step-ca
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: step-ca
  chart:
    spec:
      chart: step-certificates
      version: "1.27.x"
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Replica count (only 1 supported)
    replicaCount: 1

    # Service configuration
    service:
      type: LoadBalancer
      port: 443
      targetPort: 9000
      annotations:
        external-dns.alpha.kubernetes.io/hostname: step-ca.goldentooth.net

    # CA configuration
    ca:
      name: Goldentooth CA
      address: :9000
      dns: step-ca.goldentooth.net,step-ca.step-ca.svc.cluster.local
      url: https://step-ca.goldentooth.net
      # Database configuration - use emptyDir for learning cluster
      db:
        enabled: true
        persistent: false

    # Bootstrap configuration - auto-generate CA with JWK provisioner on first run
    bootstrap:
      enabled: true
      configmaps: true
      secrets: true

    # Resource limits
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 256Mi
