apiVersion: v1
kind: Secret
metadata:
    name: step-ca-secrets
    namespace: flux-system
type: Opaque
stringData:
    ca_password: ENC[AES256_GCM,data:CvXzKDaZPGK4B7ROK7tLztTqahWoMHsfPrO+0nhTJVE9X2ycpJ1ZLZRjOUQ=,iv:/Bqq8Zwnm4hRlXWvR/6wBl29RvioNpH4wWJfXg0RlVs=,tag:OCBbk6Kb2WsSCNO1ub1GNw==,type:str]
    provisioner_password: ENC[AES256_GCM,data:OaapkNi93Lh+/58nKnw9Md8TG27TtOjVoizGFBGTcBmvx4UL2lBQ3oepVKk=,iv:Oz4tB9A2VYzcs3VAwFGUv5TtqXiqmjtqstF8rmu+MaI=,tag:dOWkk/6v1rdU2SnUYA/rWQ==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5S0R3UmU0THBLQ3l4bGo3
            aUVseGcrNFJpLy8yU2RUa25NdVRlL0NqY0hBCndSdUFQcVo3Qk80b1I0TytQR3ZQ
            b2JsVVFIRkMxNmR2d2p5UndnbkovMncKLS0tIGx5UGZKeHhWeFFCZDd2TVZ3L1ph
            Szdpa0ZmQ3R0bjJPUERnaE81eHc3bFEKmwyFabkszisKrvUdcJZWrwkMYS3rAQqn
            ZYMtJ6ADqFNZV1iTSZ6Vi0gdRpB/WitFKPBbrP0LMWgXrmKRjOXlIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:56:13Z"
    mac: ENC[AES256_GCM,data:elgDlut+Y6QocGI3Ue5vVfm158cn4Sw80Bwg9UluJeRjA46gwmbQTc+C3Mt2FEJjq8vRZeBEMd42juy2zCYcdRWQdAPi+EBwEYP3WTt5Jdlst1VLrHoH+KGVfhjmHWYRfcyj+sXDBG8N4ujzl7KDQS+cKD0sbaHTECCwVZFSXU4=,iv:sojvjyg+h5uoRAcNwZNe8/DIP7y011fR9kIG9jvjgmI=,tag:hD1Moq106Z6nsSy+Gbbc3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
