apiVersion: v1
kind: Secret
metadata:
    name: step-ca-inject-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:GYzgzEkl3es1VUlzZ+MHx0XvN0YaCAe5KPIbrkKwVVdnvZqZWGWGGM8Xn+Iyy1y+DND/uJQAazc048jMIxsIvkBY7MQiDYy9z6jm1cj1eiCqT+Q1C4pqSgR+b8731+JlIwiHt0HqKL0j2SvPZaUOmkwArqzJkA4ShTcQKySkFINJjawu2k3cn4Iaey9TkCbOevbEnlg23bxCel2bZOHvTcRVFhjHAZv4H8cMJUSVrv5Rz6iXepTGI3O/7bSESOp8667W3UvjC/OXNQmpTP6/6s81TN4YGwwHIOglIm/mLSroIvyibZDVA/1eTm5kkP+Qau6hYCAoaUJXI7YcU7cnN4jW4yoKsuBLnQeJB4H/KjbQbTb0YOpYUfBsYrsmcLOUSmk3CtcgekViTyVJvA/IsZaI6Qsn3HL5mviTGj7RWysywV6Tsu3CGCerdPoVo3DzZyn4MTTpyVG0mKFkWpMxEsd2Q16rObUEozpMPtdnfyh0ynaPsFIhImgLqMjx5fF5vvWEh7et5fPjitmByD5aAd/3TbIMJpsw2WGMD0czYlRai+hIbQmK0PuE5G5P6ae7sB+JE22Jxq23T+LogjQSTvmnk8flI3pOMl2gBK2F0kYCFMGfSFllKiDcPllSwq/ZZBjs3G5JHrWAUWhsVDlS4ESZ4nkN9sEhL3b2NZ7bBWcHWXTVynjIfAC6iOaRTdY=,iv:KKSnoFXID5+bmC93dlRUmT9oCsWkoPpffUwYhWUz85c=,tag:otakUW0vOxxJg0QkvlMg5g==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVkJqRGxQK2pIMGk4aVFK
            SU13V2pWWnhJd2VjVmNlckxXRGo4VnF1bEQ0CkRTSmwydnM1RUJJQUZjay9yTmor
            R214TG5Ja0l1ZU1oOEZhemZuRWhqQmcKLS0tIEEyUjMxUk1ibWZqQk5VV1ZxQTJM
            RjBnVGY4MFBWcFJqMGtqdXZrMUk5NDQKGA1Dc8Pgb1B73T9oSbKuEl8pDxXiwToz
            mX39CrZZz8+25R0tiz0Xca+oMDC3gotf0jP1Y1b/tX4HsRyJLg6SQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T17:21:58Z"
    mac: ENC[AES256_GCM,data:HToeASwEPaZM5C/V/lA4yP06PExlhGSfhdXcOpj058l2rukehjbP3+S794RvHI6DYe3zUtkPxZ7Nty3ZxuYhx39+hjt2y9iKTDzDgG0jo6cJlFsNX3Fz1BwB3tyjWrjT2OvGkcndc27I6JYVi97/R9QKQ9tSlXp/6OV7NbNEkO4=,iv:tRkaeJnotxqy3mGSecrwQaAEnVbesc4kdDui+J4F4gg=,tag:ZUljqXPyvb307GegFtSrfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
