apiVersion: v1
kind: Secret
metadata:
    name: step-ca-inject-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:SoGRly7VYvkZbNc6Q+J1nm83OGnjZWEihMVhTSHN8Gwvv9Vb8JI4Akd+pHm9JFHKSaERXqsmIu9cUb5A+46SEJRnVF+69R3BJPhMJJ4hJZZm3LIjnMYRPhDdlx1sgDQD4QhuZI7sBaq8+g76XQqWzaBtIhqMpf3oA+mwINYKw7R/RROyOkxhtVoEW1LBXjmd/4apsUsmBSp+x0GWpMrT/0c8RWkMV/vjdincSOypY6b86KQKIa28vXf3lJvqLGRYl7WQtmn12+wwlIRVRNUMdx+qvuuaAmELxDERx7moSmu51s1L1Dc1dYOK+IA9atgZaZv6a3zBfYDugpZSlqEUvZDR7NgIWSPlnTHC2yFQMblGWqssnpIBOmhBdcoGbN1ImHsgLoYFg+qc6yBKjZBwkSqX43IWCf2cWaPV9xr2SY4Zch3fK1dMsvFAma3TfddM0GtN23QUixRFd08FdAMRa9cnxfwJoEYuk3b1ZG9Bpcw4cKQgY2F0CJvKiRMuoXzNFSiQX+1PEW9iyr04zcGuCCBztGwHdaYc4h/nIUd46jQ2oi2TfwyG0e98+H9+ifG0LGHBjmHMYlLTd3klz2kgTlTdjevgXHt0xBmxLSbVuG/TtLc2FRSaDTmLARlZ5AgLZ00IBHI3lh6PFByHGR0CHACKrNWy3T8pbR6ASw5ob2cdBvsUjjFYC4aGFde1+VoPceghxdXfnMCZtlnMlHRA2Z6dMgCY6+ieZN2Sktv3LBA2,iv:92IkxT4T1UYNE/02FTJG5vTiXnhJJeu9qCEN47bBPqY=,tag:9YzFtoA4DSDimqRc2bWvTg==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaUtlRTlOSnR2ekZ4QVJI
            UU9SMXUvTjk1UlMvWEt3N1dCUERCQWJUbGpBCmlqb2tJbzZXVU1qY24wV0p5Qzh3
            bXVtR3hsaWpBVHhRVHA4dW1VM3hvdHcKLS0tIFFlaUx3ZmFwWEo5R3VmMEp2OVJx
            VjVxS0luRzI4MzNBemY4TUpzMjZJQkEKabTIOIYZivZGWcCSbUSndeSJSQFm8w3y
            Qk3oFR2SnXa7rpMiz8ePI+z+5ammj6TO9ityMdESWxRnLjwb1vN5ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T17:57:51Z"
    mac: ENC[AES256_GCM,data:5k10wooV0GLQOkzhSZiqcoozpqUmfxJTM8xG4TbYt7BslvAKGqqhf6BvFvBlcVU5M26AFaXCntajsoxG+QEZkorA4xD45b6Dru3lOi8Xzmakv917jMqAbxVCYcOaQNXjmQp61ALUrnZ0juI1ALBeHiKPW/NCgW13bjj03OF53r4=,iv:6ksyZwf4buBqklIuoMkLQrMy6oQe6nd5koH7CjFrOcM=,tag:+mhj4+4UtR+QBRMGV54F7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
