apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:iDgZV3/zkluIebvDNDilfVBg41z++61zQqISH91ZI+6za9z0QHKG0Vfgmm7OR+75OfCXboWgsed9BjnjxY2KzLtDDHBizeeG2BChBOmsWc0ox151VbipfEbFRkun1Eykqk0R33gUZ2DJlETyJKA29FwTuO8n0zehB8/YZ1/xH+gZshxuW3vB/3jLYPlxGtQ3GcrN3d+deCkepCLuS3o3ZiCMX/6Mk8WYS5Zs29fDgeTKLoiO9aCh2R36B2s2xkQhYzZHFG548Og00/6nScKlUOiGEGaohuC0eMdDcVZ12AH+n3Z6XDvFksIRnu0=,iv:4KXY+V54i6eEB7gvHEPUuZtcZDDzFm+PIg+voZ9pBvY=,tag:enwAX75uk5STyKybYi8m7A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-pull
    namespace: wiz6
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOWlER3l2N21zNjN3a3Fa
            dHluTEE4VmttUkZwbjdNRGJqVkJGZU1XNlY4CkFnUW4zaGV5TVJXVVpVc0QxUlo5
            U0pqL2puWEZ6ZUpKWCsvZnV1N1Nsb0EKLS0tIDRYNmtKcXhYRm1YYnVrTW1MY3B3
            bE1HSzJyUE1uZDZiLytoY1dFMTVJaGsKNrsen2O5o97Bn9n4qSJj0CRaxv/BGqL2
            OsqZu43omE1aW8XJMrjj/QuFI4rZ+MxepcPpsEScKoeCjLrs/S7lsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-21T22:49:53Z"
    mac: ENC[AES256_GCM,data:DYUxw8HQKr8/jnm0cAp+ZaWGaYL4p6KoTXLSThoaEUpp+b9meq6jEm4xLXsVK4TAjsbLtTwPrTzVvT8uDxmIfVb4Svw49n4MXOeB1XQUXXWQMGJB7wME2kKV+zxzFCHBypwvaDj8Nu77DdbUhrKwCbsSxYeYP8EPO/tkM9afQlw=,iv:sbnVlw+qZgEnLbG5BBQeKDSsu7X7NAFue8KwqOfopdE=,tag:t1ctXwUrpK2qCZNUIetuFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
