apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldentooth-mcp
  namespace: goldentooth-mcp
  labels:
    app: goldentooth-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goldentooth-mcp
  template:
    metadata:
      labels:
        app: goldentooth-mcp
    spec:
      serviceAccountName: goldentooth-mcp
      containers:
        - name: goldentooth-mcp
          image: registry.goldentooth.net/goldentooth-mcp:3-eddd92ca6bf7a259f9f3669854c317f5f01a2884 # {"$imagepolicy": "flux-system:mcp"}
          ports:
            - name: dev
              containerPort: 8080
              protocol: TCP
            - name: auth
              containerPort: 8443
              protocol: TCP
          env:
            - name: GOLDENTOOTH_MCP_DEV
              value: "true"
            - name: RUST_LOG
              value: "info"
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
