---
# Step-CA root certificate for the private Docker registry.
# Not sensitive — this is a public CA cert, not a private key.
apiVersion: v1
kind: Secret
metadata:
  name: registry-ca
  namespace: flux-system
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBtjCCAV2gAwIBAgIQH5uxDTiYKnnh0NJ+WkSF6zAKBggqhkjOPQQDAjA6MRcw
    FQYDVQQKEw5Hb2xkZW50b290aCBDQTEfMB0GA1UEAxMWR29sZGVudG9vdGggQ0Eg
    Um9vdCBDQTAeFw0yNTExMTUyMjEyMjBaFw0zNTExMTMyMjEyMjBaMDoxFzAVBgNV
    BAoTDkdvbGRlbnRvb3RoIENBMR8wHQYDVQQDExZHb2xkZW50b290aCBDQSBSb290
    IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvZNhpjhP5b//310bvNhNqTbp
    adRuBGsF0lkySqoieja5uusUdgqro6tuakf7cs6txQ0MjKobh2eylXxVGr23dKNF
    MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
    FHSBBXddN5vJw3B/onigX8+YUQS/MAoGCCqGSM49BAMCA0cAMEQCIA/6LC8B6ods
    IC3YaUcW3NMmJ/YVq2mYvZtxI79Ej7wjAiAWfe4VbKSONyYBQks0S2H07aPThz9e
    GjLOHkp8fLHKpQ==
    -----END CERTIFICATE-----
