apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:CXNlR1GJMvtKLFxutlZAbSGk+uIEX/r3tPlTmfJ5Z7qhOrk2qlGiMD88YgljqOAOGgtWe/1fgUlereP1yI1PIEaosjA8PagQykgyHH0gfxMabI6Wuj3Mx/6M10wm8jS92XptatQAmD+p8+ei3VUJhVEeSVgdrM+BRb+A/XRba6Dv1a0M+W9yQncnoqZuhgGgNr6huF45wMLWv2P16t+UN5M2ANhZ62ECDuM0Xbn7Ed6E38kN,iv:KVPHNJYY+MZVmlo5U94B1h+uvnzeZG4vASvuKalI+3c=,tag:3uZz/F79Um9Xf/hTJty4kQ==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORTQzcGVPeG9hT2F3d3N3
            ZHIxZXV5SzhxdmdXWU1Oc0tTNEtJaHh6ZHdFCmlUYmEvV0dXQU4wdTZxY1ovM1hl
            ZmpFdXN6TXlsWDVUYnMxRHV3OThkYzgKLS0tIGhMWjdnNVB3NXBLUldKNUlqalBB
            aGR3K3VBZXVlM0JXSGJaaFNtaHllV0UK7iki9q3mmvlCx9fU7wyA6TEyzH6TWZxw
            8bupDSSFzT+Y5/MdERRz+HhiY5sTV0/W8w6925tKPJ8MYWwcy7CSPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T13:37:28Z"
    mac: ENC[AES256_GCM,data:cRqZB0M6ADMPSPUT4ZQTHwv3vtV4zatGbsuw7jixBsyRvCrdviRQo3+Ta1Oa7dByOOw8hvsvUDLagxatOgdNgoAuFObcbTcNW9aQObhvCFyeC3TPMwoW/BuDUeAxAruf+3hY6ZubzVdJzaPyoMUqtQczfdr4nBcq8yYOiFMjxc4=,iv:PIcIYDjoEIpZokvG+yDtDrF/sWvLkiZdVIJCGAYAvyU=,tag:rHmthtV7bBsdTAJ9ZQVyyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
