apiVersion: v1
kind: Secret
metadata:
    name: ddns-aws-credentials
    namespace: gateway
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:c0Q02Mpoial4PuJ8yPwLgXwOeQM=,iv:mJDHwgVaN30EooTVwANeGK2UONOILH+Co7SVZ/5yCfY=,tag:osk+Z+XZYZHpeUjBu6L0pA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:kkPGp1ceBrzjW02YhDYTbyAysbH5dMa/VFZc0rLLy31tRNz2kj4HEg==,iv:EBJO6+fLj40X6Amknuc99EHPRGE7AExnMdL2NYblFk4=,tag:eRVut0A+ucoaWZjHJUGRkQ==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UEdQMzQwcWxPdFE3V2tt
            V0FxYVJEcDR6MWF6dWZ1SUZvRTVMM0lJWG1nCkU2TjByWXNKbDNVUG9ITFhqajFP
            QXdHODkrdUpEQy9VUDNvTy93YmxaT1EKLS0tIGNZc2Npb3RTZUpaNk5jSGFNVVlR
            TnJjc3ZTM0Y0OEFsQUREaS9kSkZFZG8KncBIWJH9MbfltOVqy93FWbZg+n/b0DG2
            ncNAd5yR9ZR2k0udaX903KwTP2w1cQcge7ghy1LfCSHwHebQmndL6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T15:18:03Z"
    mac: ENC[AES256_GCM,data:upsJbfLO5drTM0BrF0RetzULR6aO1m9aVZNmAF+Uc13zSNEgHc6kmE0VF3lHjubIoapCsQjAqqhEhX6FrmnDI46QxrNL4Wax2FWQkG+vjAr8XSRngYAPhUUgFdta+W4vHCSEFUSYRogHp20wXo11ZE1JyCkdPOJCpOW4K1QvWfA=,iv:F4z6SZSLcxyfiZOpn0Jk3yvRMutneFcy19F/Z5nweXc=,tag:qgUmSgCCo3lbRGknx2DF6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
