apiVersion: v1
kind: Secret
metadata:
    name: external-dns
    namespace: external-dns
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:lw8IKMPeuq766a9TvElFTcOHxC/eCVHIa6KIqepNw30mXGEIPwZCxdk/lhC9+M6mOJdIClDsFDZp5MT6dXjqrZuomW+SmJr4Naxtu6DmCCyrWOhM5CG+iyxySDFzX7X7GW3oCaIOXB4IvR4YQZIFzIv8AdI=,iv:mL32OfBT7sOqG2AF/3PITy6/l1m3z3fxEtxjWk8X01w=,tag:+ANhDw8GOnTfOe+e+yPvOQ==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcThhL3hpbHNyMlBWdWNJ
            d3JnOHZkeDJicTk1Nm9vcU50b3VWYk9yMlhJCm9KaHpFdkJ3TGo0V3Y0RjAvMklq
            OGtQTnRNSDNJSzFPM1Axd2FETHFmTlEKLS0tIHI1ekZhbGdESUVRUVowM3RwU1pM
            VEZ6WGZwZktOakJjY1BhNGI4ZkdhMjAKtub1S+IX5iPM4jKx8niGMmaMgImG7Fzs
            AOvb5P2lAznrDdrC9xsElhISuix06vmEJrGlwurlCDQpGudOfpGwgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T23:47:55Z"
    mac: ENC[AES256_GCM,data:KtJ1EN0PaDFXCpXEq1VXpNqFsaXtWTEtxSClBRFz+QiMdZoqvOP+3usAE6bf31z9woKpRNF/rKAF09wmMcKM7saMPmHkHI6S5BayBj7tBBzLBD+5AgkOd1CpE9Q5ohne1cCkXK7d5LaOeBMJPUNYK4aEd05Kdz+aZuASHKQyCmk=,iv:T92969JeD69ZfLqZe95YXzGKPjXV+l+vLVk5JT2wKY0=,tag:6GPBGtWjW/kgWAU2WYZAyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
