---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: ntfy
data:
  server.yml: |
    base-url: https://ntfy.goldentooth.net
    listen-http: ":8080"
    cache-file: /var/cache/ntfy/cache.db
    cache-duration: "48h"
    behind-proxy: false
    attachment-cache-dir: /var/cache/ntfy/attachments
    keepalive-interval: "45s"
