---
# ClusterRoleBinding for local-path-provisioner in local-path-storage namespace
# The upstream ClusterRoleBinding gets overwritten by the USB provisioner,
# so we need our own binding to the shared ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-bind-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-provisioner-role
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-service-account
    namespace: local-path-storage
