---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage
  namespace: garage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: garage
rules:
  # Garage needs to manage its own CRD for node discovery.
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "patch", "update"]
  - apiGroups: ["deuxfleurs.fr"]
    resources: ["garagenodes"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: garage
subjects:
  - kind: ServiceAccount
    name: garage
    namespace: garage
roleRef:
  kind: ClusterRole
  name: garage
  apiGroup: rbac.authorization.k8s.io
