apiVersion: v1
kind: Secret
metadata:
    name: garage-secrets
    namespace: garage
type: Opaque
stringData:
    rpc-secret: ENC[AES256_GCM,data:5UanN0OgVCnPgzp4kqlVVQKbrDczJb0ky98FdW/G0dT5bXrJPA3LprA6PL2gBDHovZ4hQIFXSSq38tsNeYK1Aw==,iv:goLUrgghQhQtFBA6Yi0VfmKW8BKtWwunK9wpVRvY/Jo=,tag:INFK396zyget3C6fsOjfhw==,type:str]
    admin-token: ENC[AES256_GCM,data:QUnwdDlLUDQq2Yv5c0RVL3UDYJOCUrUYMWKJDn2qa83gTZxiSjUuRMvz460=,iv:UlgTsOZIeuuzivB4G2BeV2cD0IEhVw/VfWWbDMUrAoo=,tag:2preZhhWV2YYexaU7X4KAw==,type:str]
    metrics-token: ENC[AES256_GCM,data:EyAsZZoshHZvZyrGt4jqoNlTL+kMnpR8KHIL9K9+/AjC0CG5oW8obJr4z5s=,iv:rG269DFgg6VffBZGnsfh+WcPE0CN6uTptidTlwpF8lU=,tag:nV5cmW8o3oGHmeUHH6urRQ==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRmk0ZXptRGp0OUhxU2g4
            TWNmeVY1V1ROMzNhS2ZYaURQVjJkd2hYT25jClVWZFQ2MUVMZG03MHUrcldxODRv
            QlMxNDFGYWFzN2hTV1N6d0tnSXZweXMKLS0tIElXdGtybWFjL1RkOC9UNWhqUmt2
            M1B1TWtJMk1MV1FpcnBlUTEwYmVZbWMKEeuKGzttMMF2SH3jd7+LpbU130YNCN7S
            566rQ0YGiJfeZ1M30Vhu4rrHnaF3aRMfROKAR6SGeClUvXjZjFsJDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T16:22:22Z"
    mac: ENC[AES256_GCM,data:5kBTQ8oCuXu10FADEf7bIqdQN/jSizRTY0/r0C1JuncA4FGPnSBRLJaf+hbOzWW1diQwA/JTzbgLqVeXZvVrhVjW4p6heGxVrrCblFtA5u5oLaWetMOf7UuocPsKIjnW2Ro8G6x/3qFkpP+KnC8ILqGE0FDYBmo/OF1SITUOAJ0=,iv:dGblnrq95WPN44pBPgiLtegi+6zSRuvWYFYTTxVYTqI=,tag:i5hCk5hu65vJobxs+2nWPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
