# AWS credentials for cert-manager Route 53 DNS-01 solver
# Uses the same IAM user as external-dns
apiVersion: v1
kind: Secret
metadata:
    name: aws-route53-credentials
    namespace: cert-manager
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:fKYFYOp3r566vcbznJg0EQhPZ3s=,iv:FZMBJtb0NKUZTafMXkMruMRzdZ956uM3wnNoXtuo6OI=,tag:9nrRHHSq/i90xrNwXR6KvA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:P0vDQyboRMHAbM2K6ZdFDFSJgz1dFa9PmFcCbrH/JQLVZoHXiDFt0A==,iv:wnyBpHYFZ6qn6NrpNYVzxXskeH5t0vu4d0aYitTp4VU=,tag:DhEl6luRnFeBbH2Ragkcjw==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4R1lUcTIybUxJdjhrSGMx
            Mkl5UTBWaVVybENpSHNtdm54aEtHbFZYcEVFCnBLNUJnbHhZZ1NVbWh0NXo2L01l
            cUZ0Vkcvbm1BUnhzaWJjUklaZ09LK2cKLS0tIFkwNnhGSlZLUElVQmZhVXM4elov
            SThPYXJoU1NsNFY2WGR6MHJhWnlMaUkKUkHl65/SnmuYLseQTtl+LS4Q07OK4SSb
            /lDPSmK5A9ptVGFsP4rFjJ/WadtarD+vsF/1FQDjQBd5lVdBeFFgwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T20:04:19Z"
    mac: ENC[AES256_GCM,data:7Om10iUeAzCzwcZ0IuuzGmO6KYEd4D4vN6WHUix2Sjk9s3f3yaVfOFz5OQuUxTSEZ8bE8Nd6MuCVn1H0BzlPlEdOshcSG9EKhuhO/MD4OYDqbl7GCzOabcXMcs0JeMvvW6jClNExGHSiBYdaQLNHZ4OSZdbVe1yju18Vh7kU08s=,iv:2P1A5YQPOE9TLcw7p2JncvZRskDl2NjyI+tWayraGfk=,tag:SIY+mL7dUoj3/GGhF3TK1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
