---
# CertificateRequestPolicy for auto-approving step-ca certificates
# This policy allows cert-manager to automatically approve certificate requests
# that reference the step-ca StepClusterIssuer
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: approve-step-ca-requests
spec:
  # Allow requests that reference the step-ca issuer
  allowed:
    commonName:
      value: "*"
    dnsNames:
      values:
        - "*.goldentooth.local"
        - "*.goldentooth.net"
        - "*.svc.cluster.local"
        # Allow namespaced service DNS names (e.g., service.namespace.svc.cluster.local)
        - "*.*.svc.cluster.local"
    # Allow only internal cluster IP addresses (10.* range)
    ipAddresses:
      values:
        - "10.*"
    # Allow only Goldentooth organization
    subject:
      organizations:
        values:
          - "Goldentooth"

  # Enforce certificate duration limits
  constraints:
    # Maximum certificate lifetime: 24 hours
    maxDuration: 24h
    # Minimum certificate lifetime: 5 minutes
    minDuration: 5m

  # Match requests from cert-manager for step-ca issuer
  selector:
    issuerRef:
      name: step-ca
      kind: StepClusterIssuer
      group: certmanager.step.sm
