---
# CertificateRequestPolicy for auto-approving step-ca certificates
# This policy allows cert-manager to automatically approve certificate requests
# that reference the step-ca StepClusterIssuer
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: approve-step-ca-requests
spec:
  # Allow requests that reference the step-ca issuer
  allowed:
    commonName:
      value: "*"
    dnsNames:
      values:
        - "*.goldentooth.local"
        - "*.goldentooth.net"
        - "*.svc.cluster.local"
    # Allow any IP address
    ipAddresses:
      values:
        - "*"

  # Match requests from cert-manager for step-ca issuer
  selector:
    issuerRef:
      - name: step-ca
        kind: StepClusterIssuer
        group: certmanager.step.sm
