---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acme-certificate-request-policy.yaml
  - acme-cluster-issuer.yaml
  - aws-route53-secret.yaml
  - certificate-request-policy.yaml
  - policy-rbac.yaml
  - step-cluster-issuer.yaml
  - letsencrypt-cluster-issuer.yaml
