---
# StepClusterIssuer for step-ca using JWK provisioner
# This allows any namespace to request certificates from step-ca
# using the admin JWK provisioner created during bootstrap
apiVersion: certmanager.step.sm/v1beta1
kind: StepClusterIssuer
metadata:
  name: step-ca
spec:
  # step-ca URL
  url: https://step-ca.step-ca.svc.cluster.local

  # CA root certificate (base64 encoded PEM)
  # NOTE: This is generated during bootstrap. If step-ca is recreated,
  # update this value by running:
  # kubectl get configmap -n step-ca step-ca-step-ca-step-certificates-certs \
  #   -o jsonpath='{.data.root_ca\.crt}' | base64 -w 0
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ0akNDQVYyZ0F3SUJBZ0lRSDV1eERUaVlLbm5oME5KK1drU0Y2ekFLQmdncWhrak9QUVFEQWpBNk1SY3cKRlFZRFZRUUtFdzVIYjJ4a1pXNTBiMjkwYUNCRFFURWZNQjBHQTFVRUF4TVdSMjlzWkdWdWRHOXZkR2dnUTBFZwpVbTl2ZENCRFFUQWVGdzB5TlRFeE1UVXlNakV5TWpCYUZ3MHpOVEV4TVRNeU1qRXlNakJhTURveEZ6QVZCZ05WCkJBb1REa2R2YkdSbGJuUnZiM1JvSUVOQk1SOHdIUVlEVlFRREV4WkhiMnhrWlc1MGIyOTBhQ0JEUVNCU2IyOTAKSUVOQk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXZaTmhwamhQNWIvLzMxMGJ2TmhOcVRicAphZFJ1QkdzRjBsa3lTcW9pZWphNXV1c1VkZ3FybzZ0dWFrZjdjczZ0eFEwTWpLb2JoMmV5bFh4VkdyMjNkS05GCk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRRXdIUVlEVlIwT0JCWUUKRkhTQkJYZGRONXZKdzNCL29uaWdYOCtZVVFTL01Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lBLzZMQzhCNm9kcwpJQzNZYVVjVzNOTW1KL1lWcTJtWXZadHhJNzlFajd3akFpQVdmZTRWYktTT055WUJRa3MwUzJIMDdhUFRoejllCkdqTE9Ia3A4ZkxIS3BRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

  # JWK Provisioner configuration
  provisioner:
    # Provisioner name from bootstrap
    name: admin

    # Key ID from bootstrap ConfigMap
    # NOTE: This is generated during bootstrap. If step-ca is recreated,
    # update this value by running:
    # kubectl get configmap -n step-ca step-ca-step-ca-step-certificates-config \
    #   -o jsonpath='{.data.ca\.json}' | jq -r '.authority.provisioners[0].key.kid'
    kid: gNmIYw4NLWUVXHBpt4UcewBXd2olt1fLFC241p1IyCE

    # Reference to provisioner password secret
    passwordRef:
      name: step-ca-step-ca-step-certificates-provisioner-password
      key: password
