apiVersion: v1
kind: Secret
metadata:
    name: pds-backup-credentials
    namespace: pds
type: Opaque
stringData:
    SEAWEEDFS_ACCESS_KEY: ENC[AES256_GCM,data:x2f+/qA=,iv:SQ2tScmkH7OxKTMDdT1OMdAgUDkWniyXdmx4p6B77g0=,tag:4dbZE9wcH1mDIX6Ulm/7oQ==,type:str]
    SEAWEEDFS_SECRET_KEY: ENC[AES256_GCM,data:3z2zGrH6c3PMeSGNlt+dfjgj2wge+aMoijAQb8mWaj92Kj7b5nIUtb4nTkM=,iv:Xk8ek+7x1Lcy8r43j7PmyiL/JJQGcZf+ejj1VbB/134=,tag:apClk5BELkLJgzcHD76F5g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pHaBQ48RNmasqiZ2kNkiRdRKJ2U=,iv:V+o/nM+QLqtvrEty5y30B4/TorXJE72RZrXxEE59xyY=,tag:wMSGXzDUgsqloIrhfaPfAA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IWCBi5RuXKndTuxEbxqLLw5d9vdE/f2bg3+za8RWdIRL7suxAVyPjA==,iv:5NKMIzzAWV9gGCNWWQxHKUuUtdN4unUl156ap10nPG0=,tag:KHELaYRVKR3/WUsM2ixBAA==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRWpyQk1EVjRqOWtCZnN1
            NnV4Zkx2VE0vVXN4elpVT1k1NFUwVnJWVWo4CitjZTh3VGFzWW1PQ1hXNkxBRlZu
            ZmJmUTB3Rm1wN3RaUEhJL3dsVVc1RTgKLS0tIEZINEJSUmZOR2pkZ0c4eEo1MG14
            T0RhQkdIZmE0MHU4S1RqWXAxR0Q1RlUKtHALsWiy/0w2bHjcomeUf3RTB+d/KXjg
            04FvSJlF57aJkAMZsaeTblKp/vIIs5Yw9p2UjEFnV1vlenasynxZ4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T20:07:58Z"
    mac: ENC[AES256_GCM,data:yd6L1BGJdyOn4ihY4WBgqxD3VZqpKVBlPfQjuacdF7jkUrCE77LNICaGrMxQlsyjHcWR8R68pRQ0ymLvVDplapJ9lzB8RrQfZv0pzh7xevSft89FcWY1keNzD1aFe1oIplxmxquWs/z5XkrM3n8brm9syrS8k21I6jzKMa3Ayn8=,iv:58u9ZCfknbjolOJyfdBOPEg8oGDNA0a7VFbDRU8iQTA=,tag:7t6NaL3dRdCCgTgS7vFvXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
