apiVersion: v1
kind: Secret
metadata:
    name: pds-backup-credentials
    namespace: pds
type: Opaque
stringData:
    SEAWEEDFS_ACCESS_KEY: ENC[AES256_GCM,data:7I4IXLY=,iv:l3xRPn121AJgZsEbMaOXttAw8AVKhZb8kZwVFuzaap4=,tag:Iv8YmG8J5YRqQ4K82QDnfA==,type:str]
    SEAWEEDFS_SECRET_KEY: ENC[AES256_GCM,data:VUQEvulKD1j3icgKBcuKs98c7Wyuq+tsWUXak+gU+tJBvNW42UhiSWbbd6U=,iv:g7lD1CigsvDZqDToLLsFLRMyKtFU5F2zyFa3Dfxz6D4=,tag:SgWr9DUo91hxG53D1fhjAQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:O1Iz/UIQH9P7AOm58COpff5Q0iM=,iv:9T5sHAAXtZMouHiWYIrKKuOKJQxkvNX1mRk2rubuubo=,tag:jrLbRNReqfcI+hPAcgXBuw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:O9FudKuPWklAfMY7aAU9kogGVbcvAh5jTyTYul1gRFaasv0i7484PQ==,iv:qGwQDDsbGFYtW55RNmgeION49Y9U7yYgRZPB/DFfW4A=,tag:c0QLeK3FhsJNjJJ5Q6nxDw==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYlBaUWRWdnNTTHVIUlB0
            bUZLZXMvdnRGU016UHZObjZyRGU2ZEZGWlNFCnRLZVhaZUFwVHRQZ1lWZU5FSGp5
            c1c5YVlOUWd5dHk2NHIxdnFPMDZFOWcKLS0tIGlGUGtwaU1kN1NFNmpSV0g1MVhy
            dWVESUVmOWxteVl4dGlwM1FBcXJDYmcKNCmQESSAVzBZLKxcnj50v6OVYsS+o+96
            fjeH923fvhFp8wdR8kQKD0iSSUyqqi41CT7TqgWksKTkXXQpzErfwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T13:37:28Z"
    mac: ENC[AES256_GCM,data:XdXn++HqGPRag2rixPZ+Q9N+qRwa2LMJRfhhY7YZSUMoSEKdvPecc9HZQSaIAOJGwz2fIIYpX79PdaCHYw1cdOlLy6SZzNvnYHLNKbgHIMOT/pkf8fEjTa9zpRpnkkwgZj7izzCFePDpAjrIfk49in11Yqz06EmQMx2uwYvSpcg=,iv:kdGigBFg9zcrlpA/dA26icHYGEZF5gvQNHT0lULVDBs=,tag:5hgpitidhy9aRgBQIj+6Ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
