---
apiVersion: v1
kind: Secret
metadata:
  name: pds-backup-credentials
  namespace: pds
type: Opaque
stringData:
  SEAWEEDFS_ACCESS_KEY: REPLACE_BEFORE_SOPS_ENCRYPT
  SEAWEEDFS_SECRET_KEY: REPLACE_BEFORE_SOPS_ENCRYPT
  AWS_ACCESS_KEY_ID: REPLACE_BEFORE_SOPS_ENCRYPT
  AWS_SECRET_ACCESS_KEY: REPLACE_BEFORE_SOPS_ENCRYPT
