apiVersion: v1
kind: Secret
metadata:
    name: pds-env
    namespace: pds
type: Opaque
stringData:
    PDS_JWT_SECRET: ENC[AES256_GCM,data:9ozQzaQ5a3rSw5e0VxAne9lpDg/ggSn1veXWvzmLtFE=,iv:B4VZXlwBvHjjzQXf+pPkI95Ve7cZ+sxqSee6Dzsh2wU=,tag:gm2z4/4yzP7eWs42F+uOTQ==,type:str]
    PDS_ADMIN_PASSWORD: ENC[AES256_GCM,data:lisRTeDxlKKbeDVVTmbM77p+b8YrmHQdjl2VyyvJUTA=,iv:7prIqHBzvbXUIW05DjlSgR5Yy0Krl6Ej0JPzy7C4qic=,tag:XUEFD4X4o5r3abGd0e2YIg==,type:str]
    PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:ccvnajwuRIIuLYbH/yUUTRbWJ6X5d/ViyvLC0WlHoEJ9c/04ES7GqItx+RMZEhnAIENREbllJGJZ6PccdlTfyA==,iv:S8DItL1mie0xiobfqqBZp1ZAZwpMgcz4uo3fXaUTSY0=,tag:H0dNHOFZgPMYswuHS5P39Q==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQWtYR3YrNEEvQlFSSlBu
            Szl5TmhyMGxuK0dVMkVEbW1CSnJvTnZmVWdBCkErY0NyRzBHMzgzSFloL053Si9C
            MUVLVG9tM3JJdDNtTkVaRG04UlJZTGcKLS0tIEZiWU9TbnMzTVFQUzNTZG55cDlQ
            ZzJxbTBsZ2R4RUVSM2h0bHlzSkVQelEKuLW2T3CNwpsToTNjMqG/TuTuTq4+Mz+x
            TbON4735iPEDMtkKngEwX0RYSu7WVx6PqrE58PyVf/QhiGTSbGKz0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T13:37:28Z"
    mac: ENC[AES256_GCM,data:QL3KTslvL0Vh6cTOm6ApEk/BHWiLxYgmob/24XoQh/EtStv/hwW2Ee35l/XOyExd7uo0P+MYhXcS7KtFleq6e7vGJ1tLfU6s1RY8K7LRHjushUCSuYIvCjl2d/iptTwwyRUNskXh7gEvXlTaarM/D9siFaHV2cryb3VCcjZeQis=,iv:ieOIct4oaI9SosPFsN8AnJhjECTg1iMl/xKtuALOgAM=,tag:zvKn+DUkKdX2tVnjAtD1Zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
