---
apiVersion: v1
kind: Secret
metadata:
  name: pds-env
  namespace: pds
type: Opaque
stringData:
  PDS_JWT_SECRET: REPLACE_BEFORE_SOPS_ENCRYPT
  PDS_ADMIN_PASSWORD: REPLACE_BEFORE_SOPS_ENCRYPT
  PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: REPLACE_BEFORE_SOPS_ENCRYPT
