---
apiVersion: v1
kind: Namespace
metadata:
  name: seaweedfs
  labels:
    # SeaweedFS volume servers and CSI driver need hostPath access
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
