---
# SeaweedFS namespace for distributed object storage
# Provides S3-compatible storage for Harbor registry and other services
apiVersion: v1
kind: Namespace
metadata:
  name: seaweedfs
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: storage
