apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-credentials
    namespace: seaweedfs
data:
    seaweedfs_s3_config: ENC[AES256_GCM,data:ES8ZVdrbVz5xnBqEmaaWrP+RKk+HDak91QCi+1S6Gqc9NcKPcvja85qw5wRJlLE0kC7nfWxIOm/FopxV+azVxjqQlO3RDlpEoXP7RnFwvnRL2Upmy8DdU8f87/dIaMYZCO5oCRuFE9WK0fjLxiNFXXIZFnZ+aI+NHMDCSM3TF1//gKHCYRe1bM5JlWTcqQmVJNut1ao34O5SENWfzREbTIfQai0jnEhY2YATbSD8dOd2AYDLYGd/GqRKG0qisEN+DjjWAFEk3Qy6uhfIUQZJJI/CoDY+LnA/3o1Kg/qa/GXabOHMZUdZlCIPfzPtvN6aQPFxCgi8Tx9BktkqE3EdDWfetJOC/Gu+We4N/EAVQ0feFFPFzMPhAV+QpNXagcKNdi/e5sdVLT+Btue1CIzS/7ODflduFgjj18Eog4+Ej7HhbMsXqaG5mkyXoYyuaoIO4gEOSj9FBCjxYtErfDHDaOhq+WkN2soJmv8hWmtKXxcNIn74rPw/sgFtWkQB0Jw4bL9uI64P+5PgfDbjBYBMTgrJuoIc+tt10Uepq/mTxSd6Y1QEA78xcGqnaDjXY/ouQqbSaerBhhP0ASx5gLZpUZRgPvw2C3MABbPNwEHGdO/5xDmzspvNr1QNkAQ3pbTcDdYCkymWiQbKd84UMRAuC2yW4ifBATyGq40NRBlnJjBUTVEkKHhG8GYD+ASQGb+4sUxrYX7kky5zNybX0zFLVVT33yyR9mtT423TMrTHYzxAI8EC68J1J/MPnuGIFoN9fKc6OtOQpnLhT+bhaW1bJkPXU7EsBT30kQtQo1SpcVw1Dbf7MkJDJb7NpSIZZ/c989/UjKOlLSp4ltmNhyW5ALVsTuswKqzYGjiKVSDJXuzdp0Wo33ZKhhfgC7fAXUCIri+ZkaIhTIENnGhfMoEqvI/ts0E9whA0,iv:zQ4FjRwMAjs8H+pzaJ9PiC6fn3RgUIDRJnWPGLhmxd8=,tag:z5V6SOYpnOxE0ZBY8Lyjfw==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdUxoc3NpU3ZBUEF4OGFq
            UzNQZkFxZE5GRldzai9RQXRJWGNXQUVlUjM4CnFRdjVHZEdRamt3VDRaL05lakFx
            Y1Y3bkFhVWUvQUVNOHdTUTJFWVdmVXMKLS0tIERKd05JRkVOTUFjSTV0dnhKaDdo
            MC96eTZ3L0Q0WXU4eVBlRXNiSUlrL1kKF04r9+/bNDd+WknkuUJsovHep1pFRr8Q
            Dn57tuqDBQl0vpordb3+PsBeRSR9RDehW15zHpJjXiQzLMNpEi8sLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T19:32:27Z"
    mac: ENC[AES256_GCM,data:/DbuNqLrZ6qIS1sBSH2aKfHC9A1fGEYizL0ih7zskST/dDMbDUKP0dbt+4HJ4UDRENiw6iGvRKtH62SeY93sP8EmvsmjJGu7P2x2k1dTEa9S1dEAn3CCZfXyR0cwQ7RihBkV8gjJIqeXY5fqKnS9tyAqbpMZvdJYf38D01aa9Q8=,iv:2A/MVNuvHJvd6qMXk5oUKunNSvYdoGU41Xbpln7R1qE=,tag:S6uHjXb5EwIPMf/Ic/FxoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
