---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - metallb
  - external-dns
  - nvidia
  - pki
  - local-path-provisioner
  - local-path-usb-provisioner
  - prometheus-stack
  - prometheus-node-exporter
  - prometheus-blackbox-exporter
  - chaos-mesh
  - falco
  - docker-registry
  - loki
  - tempo
  - alloy
  - netboot
  - ntfy
  - seaweedfs
  - gateway-crds
  - gateway
  - nic-watchdog
  - metrics-server
  - nats
patches:
