---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - metallb
  - external-dns
  - nvidia
  - pki
  - local-path-provisioner
  - local-path-usb-provisioner
  - kubevirt
  - prometheus-stack
  - prometheus-node-exporter
  - prometheus-blackbox-exporter
  - litmus
  - tekton
  - docker-registry
  - loki
  - tempo
  - alloy
  - netboot
  - ntfy
  - longhorn
  - garage
  - gateway-crds
  - gateway
  - nic-watchdog
patches:
