---
# Grafana Datasource ConfigMap for Loki
# Grafana auto-discovers this via the grafana_datasource label
# and adds Loki as a queryable datasource
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://monitoring-loki.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000
