---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: httpbin
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./apps/httpbin
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: httpbin
  timeout: 3m0s
  wait: true
