---
# Flux Kustomization for Steam-Headless gaming container
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: steam-headless
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./apps/steam-headless
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: steam-headless
  timeout: 5m0s  # Longer timeout - container image is large (~8GB)
  wait: true
