apiVersion: v1
kind: Secret
metadata:
    name: harbor-s3-secret
    namespace: harbor
type: Opaque
stringData:
    accesskey: ENC[AES256_GCM,data:v6TYVKlH,iv:jjGGdK4SWtQKlasjRP4C/HfvDdpaHomcUBUUAMp6dIs=,tag:tot2z5qND5ySrYechZKRlA==,type:str]
    secretkey: ENC[AES256_GCM,data:ISzPS6in2wOloE8mNPgp8hIl0hX5tXKyPpcwgvp8whv+hVfaOZ4Q3oTRPb0=,iv:4+thp1PjQjZsP5h7J1UeirrFPwF9InQ1JKPRDCfVVOk=,tag:62G0VeXA2HAFmUyl8+YqGg==,type:str]
sops:
    age:
        - recipient: age179hfp3n7e42d2fazj09tvjjxpav6ztr3z98g0hwaxpunyfd7rcnqcv0x27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSC80TitUenpBUkt2ejZG
            V21pT1dHWFF6L2JyV1VJVXYydXR4c1N0T2owCkJKaVFTM0hnS0U1YUptbEZxT2Nq
            UWhRaWxobzg0OXZyOEdZU3h1SkQ0aGsKLS0tIDNFSTk4aTBGYTNvYXNFOFRDbFR4
            M0NlVzczK3IzOGozS2JDSGxJUDErZTAK2vuK92pIIkA0GNnCvhQHSUi+lhsD9RUt
            yX/w6m5N8I4SJ8+9P/LdIojXnnxM8KBAf+zIyFpyqKvqsqaGf6xIGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T18:00:15Z"
    mac: ENC[AES256_GCM,data:ehmxGOvycW6V7XJbnwvc4TkaSVRu3le+HXit/2CZMIdmTiyxPm2Wykn9ahcsaq9giofaLgXFFrHpY3mRVTpJXNuxalkCoN3meDtBf5VscG5zNokKlohEIV5QEk7ApuV5xNZsh43mr/9MhGKWUKqRFoDEzkqyKyfIjg1odVxSM50=,iv:uf5GIT+z05YBUas2YM9ZGSakRwtAdCWWMgMZYfurHBc=,tag:TlxZ2z6Qmi3VZNvbeN4Pvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
