---
# CDI (Containerized Data Importer)
# For automatic VM disk image import
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cdi
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/kubevirt/containerized-data-importer
  ref:
    tag: v1.61.1
  ignore: |
    /*
    !/manifests/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt-cdi
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: cdi
  dependsOn:
    - name: kubevirt-operator
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cdi-operator
      namespace: cdi
