---
# KubeVirt operator via remote kustomize resources
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/kubevirt/upstream
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: virt-operator
      namespace: kubevirt
