---
# KubeVirt Operator
# Deployed via direct manifest from GitHub releases
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubevirt
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/kubevirt/kubevirt
  ref:
    tag: v1.6.3
  ignore: |
    /*
    !/manifests/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubevirt
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: virt-operator
      namespace: kubevirt
