apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubevirt-operator
  namespace: kubevirt
spec:
  interval: 30m
  chart:
    spec:
      chart: kubevirt-operator
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: kubevirt
        namespace: kubevirt
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # KubeVirt operator configuration
    spec:
      # Enable feature gates for GPU passthrough
      configuration:
        developerConfiguration:
          featureGates:
            - GPU
            - HostDevices
            - HotplugVolumes
