---
# HelmRepository for SeaweedFS Operator
# Provides the operator charts that manage SeaweedFS clusters declaratively
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: seaweedfs-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://seaweedfs.github.io/seaweedfs-operator/
